#![allow(unused_imports, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod getcamelotv3pooldatabatchrequest;
pub mod icamelotv3pool;
pub mod ierc20;
pub mod bitmath;
pub mod getcamelotv3tickdatabatchrequest;
pub mod icamelotv3poolstate;
pub mod getcurvepoolbatchrequest;
pub mod icurvepool;
pub mod getdetailedpooldatabatchrequest;
pub mod geterc4626vaultdatabatchrequest;
pub mod ierc4626vault;
pub mod getuniv2pooldata;
pub mod getuniv3pooldata;
pub mod getuniswapv2pairsbatchrequest;
pub mod ifactory;
pub mod getuniswapv2pooldatabatchrequest;
pub mod iuniswapv2pair;
pub mod getuniswapv3pooldatabatchrequest;
pub mod getuniswapv3tickdatabatchrequest;
pub mod iuniswapv3poolstate;
pub mod getve33poolsbatchrequest;
pub mod getwethvalueinpoolbatchrequest;
pub mod iuniswapv2factory;
pub mod iuniswapv3factory;
pub mod iaerodromeclpool;
pub mod iaerodromepool;
pub mod ierc165;
pub mod ierc721;
pub mod ierc721enumerable;
pub mod ierc721metadata;
pub mod ierc721tokenreceiver;
pub mod iuniswapv2pool;
pub mod iuniswapv3pool;
pub mod mockerc20;
pub mod mockerc721;
pub mod synccamelotv3poolbatchrequest;
pub mod syncuniswapv3poolbatchrequest;
